### ISSUE TITLE
Deploy fast_script to 0.1.5

### ISSUE THREAD

**Issue by erikgaas** [fastai/fastscript#6]
Some bugs were fixed by this PR https://github.com/fastai/fastscript/pull/3 which are not reflected in pypi. Last time this was done was in early January. (https://pypi.org/project/fastscript/#history)

Just a friendly request to push the most recent codebase. Thanks!

**Comment by methuselah-0** [comment]
Note that settings.ini is not part of the files in the tarball that ends up in pypi: https://pypi.org/project/fastscript/#files which you might want to fix.

**Comment by jph00** [comment]
Sorry I missed this - feel free to at-mention me if I don't notice something!
